# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  'build':
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
  
workflows:
  version: 2
  build:
    jobs:
      - 'build'
